services:
  # News Ingestor Service
  ingestor:
    build: .
    container_name: nexnews-ingestor
    command: python -u ingestor_start.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - nexnews-network
    depends_on:
      - api

  # API Service : Separate container for Availability and Scalability
  api:
    build: .
    container_name: nexnews-api
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - nexnews-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nexnews-network:
    driver: bridge